const colors = {
  red: '#d76a5f',
  green: '#65cf70',
  yellow: '#cae164',
  orange: '#e1a064',
  grey: '#555d5d',
}

const actions = [
  {name: 'Raid - ludzie', cost: 90, color: colors.red},
  {name: 'Raid - insekty', cost: 100, color: colors.red},
  {name: 'Raid - mechy', cost: 200, color: colors.red},
  {name: 'Choroba Kolonistów', cost: 700, color: colors.red},
  {name: 'Zaraza Plonów', cost: 370, color: colors.red},
  {name: 'Psychiczne brzęczenie', cost: 350, color: colors.red},
  {name: 'Karawana', cost: 200, color: colors.green},
  {name: 'Kolonista dołącza', cost: 450, color: colors.green},
  {name: 'Kapsuła z lootem', cost: 90, color: colors.green},
  {name: 'Fala Zimna', cost: 400, color: colors.red},
  {name: 'Fala Gorąca', cost: 400, color: colors.red},
  {name: 'Meteoryt', cost: 200, color: colors.grey},
  {name: 'Infestation', cost: 200, color: colors.red},
  {name: 'Burza z piorunami', cost: 60, color: colors.orange},
  {name: 'Spięcie Obwodów', cost: 70, color: colors.orange},
  {name: 'Alfa Bobry', cost: 150, color: colors.red},
  {name: 'Klaster Mechów', cost: 740, color: colors.red},
  {name: 'Radioaktywna Chmura', cost: 400, color: colors.red},
  {name: 'Deszcz Meteorytów', cost: 350, color: colors.grey},
  {name: 'Susza', cost: 400, color: colors.red},
  {name: 'Zima wulkaniczna', cost: 500, color: colors.red},
  {name: 'Gaj ambrozji', cost: 200, color: colors.yellow},
  {name: 'Event zwierze', cost: 150, color: colors.yellow},
  {name: 'Wczytanie', cost: 800, color: colors.green},
  {name: 'Zorza Polarna', cost: 150, color: colors.green},
  {name: 'Plony Obrodziły', cost: 400, color: colors.green},
  {name: 'Słoneczny rozbłysk', cost: 300, color: colors.red},
  {name: '10 minut spokoju', cost: 600, color: colors.green},
  {name: 'Anuluj 10 minut spokoju', cost: 800, color: colors.red},
  {name: 'Bitwa Kosmiczna', cost: 400, color: colors.grey},
  {name: 'Trzęsienie Ziemi', cost: 400, color: colors.red},
  {name: 'Samooswojenie', cost: 150, color: colors.yellow},
  {name: 'Zaćmienie', cost: 300, color: colors.red},
  {name: 'Toksyczny Statek Mechów', cost: 650, color: colors.red},
  {name: 'Żebracy', cost: 150, color: colors.grey},
  {name: 'Thrumbo', cost: 150, color: colors.grey},
  {name: 'Wroga Karawana', cost: 250, color: colors.orange},
  {name: 'Herd Migration', cost: 150, color: colors.yellow},
  {name: 'Quest', cost: 150, color: colors.yellow},
  {name: 'Zasmuć', cost: 150, color: colors.orange},
  {name: 'Psychiczne Kojenie', cost: 350, color: colors.green},
  {name: 'Orbitalny Handlarz', cost: 200, color: colors.yellow},
  {name: 'Spadający odłamek statku', cost: 70, color: colors.yellow},
  {name: 'Dzikus się przybłąkał', cost: 70, color: colors.grey},
  {name: 'PSI Statek Mechów', cost: 650, color: colors.red},
  {name: 'Uszczęśliw (+10)', cost: 150, color: colors.yellow},
  {name: 'Boskie Uzdrowienie', cost: 450, color: colors.green},
  {name: 'Piorun', cost: 600, color: colors.grey},
  {name: 'Zmiana Ideologii', cost: 150, color: colors.yellow},
  {name: 'Zmartwychwstanie', cost: 800, color: colors.green},
  {name: 'Sfora Ludojadów', cost: 100, color: colors.red}
]
export default actions;
