const actions = [
  {name:'Raid - ludzie', cost:90},
  {name:'Raid - insekty', cost:100},
  {name:'Raid - mechy', cost:200},
  {name:'Choroba Kolonistów', cost:700},
  {name:'Zaraza Plonów', cost:370},
  {name:'Psychiczne brzęczenie', cost:350},
  {name:'Karawana', cost:200},
  {name:'Kolonista dołącza', cost:450},
  {name:'Kapsuła z lootem', cost:90},
  {name:'Fala Zimna', cost:400},
  {name:'Fala Gorąca', cost:400},
  {name:'Meteoryt', cost:200},
  {name:'Infestation', cost:200},
  {name:'Burza z piorunami', cost:60},
  {name:'Spięcie Obwodów', cost:70},
  {name:'Alfa Bobry', cost:150},
  {name:'Klaster Mechów', cost:740},
  {name:'Radioaktywna Chmura', cost:400},
  {name:'Deszcz Meteorytów', cost:350},
]
export default actions;
